FROM ros:jazzy

# Aggiorna i pacchetti una sola volta all'inizio
RUN apt update -y && apt upgrade -y

# Installa tutti i pacchetti in un'unica RUN per ridurre layer
RUN apt install -y \
    ros-jazzy-turtlesim* \
    ros-jazzy-rqt-graph \
    wget \
    liburdfdom-tools \
    ros-jazzy-urdf-launch \
    ros-jazzy-rviz2 \
    ros-jazzy-joint-state-publisher-gui \
    ros-jazzy-robot-state-publisher \
    libogre-1.12-dev \
    build-essential \
    python3-dev \
    python3-colcon-common-extensions \
    python3-pip \
    git

# Pulisci la cache apt
RUN apt clean && rm -rf /var/lib/apt/lists/*